name: Waka Readme

on:
  schedule:
    # Runs every 4 hours
    - cron: "0 */10 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TITLE: true
          TIME_RANGE: all_time
          SHOW_TIME: true
          SHOW_MASKED_TIME: true
