name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am with local timezone
    - cron: "0 0 * * 0"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-22.04
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TOTAL_CODE_TIME: "True"
          SHOW_LANGUAGE: "True"
          SHOW_OS: "True"
          SHOW_EDITORS: "True"
          SHOW_LANGUAGE_PER_REPO: "True"
          SYMBOL_VERSION: 1
